title: [Mukesh Kumar Singh | Cyber Security | Artificial Intelligence | Machine Learning]
description: [Mukesh Kumar Singh | Cyber Security | Artificial Intelligence | Machine Learning | Deep Neural Networks | NLP |LLM]

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
