(function(){
  const works=[
    ["llm-security-playbook.html","LLM Security Playbook","AI Security"],["ai-security-playbook.html","AI Security Playbook","AI Security"],["Real-Time-Network-Anomaly-Detection.html","Real-Time Network Anomaly Detection","Detection"],["windows-forensics-framework.html","Windows Forensics Framework","Digital Forensics"],["digital-evidence-framework.html","Digital Evidence Framework","Digital Forensics"],["cti-framework.html","Cyber Threat Intelligence Framework","Threat Intelligence"],["threat-hunting.html","Threat Hunting Project","Detection"],["digital-forensics-handbook.html","End-to-End Digital Forensics Handbook","Digital Forensics"],["kape-autopsy-automation.html","KAPE & Autopsy Enterprise Automation","Digital Forensics"],["osint-framework.html","OSINT Framework","Threat Intelligence"],["human-hacking-framework.html","Human Hacking Framework","Security Research"],["auditing-logging-guidelines.html","Auditing & Logging Guidelines","Security Foundations"],["rhel-hardening-guidelines.html","RHEL 3.0 Hardening Guidelines","Security Foundations"]
  ];
  document.body.classList.add("research-detail");
  const header=document.querySelector(".site-header");
  if(header) header.innerHTML='<div class="container"><div class="navbar"><div class="logo"><a href="index.html">MKS.</a></div><button class="detail-menu mobile-menu-btn" type="button" aria-expanded="false" aria-controls="detail-nav">Menu</button><ul class="nav-links" id="detail-nav"><li><a href="index.html">Home</a></li><li><a href="index.html#profile">Profile</a></li><li><a href="journal.html">Journal</a></li><li><a href="index.html#research">Research</a></li><li><a href="index.html#collaborate">Collaborate</a></li></ul></div></div>';
  const btn=document.querySelector(".detail-menu"),nav=document.querySelector("#detail-nav");if(btn&&nav){btn.addEventListener("click",()=>{const open=nav.classList.toggle("show");btn.setAttribute("aria-expanded",String(open));btn.textContent=open?"Close":"Menu"})}
  const file=location.pathname.split("/").pop()||"";const pos=works.findIndex(w=>w[0]===file);const main=document.querySelector("main.main-content")||document.querySelector(".main-content");
  if(main&&pos>=0){const prev=works[(pos-1+works.length)%works.length],next=works[(pos+1)%works.length],related=works.filter((w,i)=>i!==pos&&w[2]===works[pos][2]).slice(0,3);const wrap=document.createElement("section");wrap.className="research-nav";wrap.innerHTML='<p class="research-nav-title">Continue through the archive</p><div class="research-nav-grid"><a href="'+prev[0]+'"><span>Previous work</span><strong>← '+prev[1]+'</strong></a><a href="'+next[0]+'"><span>Next work</span><strong>'+next[1]+' →</strong></a></div>'+(related.length?'<div class="related-work"><h2>Related work</h2><div class="related-links">'+related.map(w=>'<a href="'+w[0]+'">'+w[1]+' ↗</a>').join("")+'</div></div>':"");main.insertAdjacentElement("afterend",wrap)}
  const footer=document.querySelector(".site-footer");if(footer)footer.innerHTML='<div class="container footer-content"><span>© 2026 Mukesh Kumar Singh</span><div class="social-links"><a href="journal.html">Journal</a><a href="index.html#research">Research</a><a href="mailto:contact@mukeshkumarsingh.com">Email</a><a href="https://linkedin.com/in/mukeshkumarsingh11" target="_blank" rel="noopener">LinkedIn</a><a href="https://x.com/oda3institute" target="_blank" rel="noopener noreferrer">X / Twitter</a></div></div>';
})();
