const research=[
 {title:"LLM Security Playbook",year:"2024",area:"AI Security",desc:"Prompt injection, model supply-chain risk, and practical safeguards for large language model deployments.",href:"llm-security-playbook.html"},
 {title:"AI Security Playbook",year:"2024",area:"AI Security",desc:"Adversarial machine learning, privacy-preserving techniques, model security, and secure AI deployment.",href:"ai-security-playbook.html"},
 {title:"Real-Time Network Anomaly Detection",year:"2025",area:"Detection",desc:"A containerized detection pipeline combining network telemetry, IDS tooling, and unsupervised machine learning.",href:"Real-Time-Network-Anomaly-Detection.html"},
 {title:"Windows Forensics Framework",year:"2025",area:"Digital Forensics",desc:"Evidence acquisition and analysis across registry, browser, system, and removable-media artefacts.",href:"windows-forensics-framework.html"},
 {title:"Digital Evidence Framework",year:"2025",area:"Digital Forensics",desc:"Collection, storage, processing, and presentation practices for defensible digital evidence handling.",href:"digital-evidence-framework.html"},
 {title:"Cyber Threat Intelligence Framework",year:"2025",area:"Threat Intelligence",desc:"Collection, analytic models, handling protocols, and threat-informed defensive application.",href:"cti-framework.html"},
 {title:"Threat Hunting Project",year:"2025",area:"Detection",desc:"Hypothesis-led hunting, ATT&CK-informed analysis, and detection-engineering practices.",href:"threat-hunting.html"},
 {title:"End-to-End Digital Forensics Handbook",year:"2025",area:"Digital Forensics",desc:"An open-source practitioner handbook covering tools, techniques, and end-to-end DFIR processes.",href:"digital-forensics-handbook.html"},
 {title:"KAPE & Autopsy Enterprise Automation",year:"2025",area:"Digital Forensics",desc:"Incident-response and disk-forensics automation using KAPE, Autopsy, and Solr.",href:"kape-autopsy-automation.html"},
 {title:"OSINT Framework",year:"2025",area:"Threat Intelligence",desc:"A modular open-source intelligence workflow for threat detection and situational awareness.",href:"osint-framework.html"},
 {title:"Human Hacking Framework",year:"2025",area:"Security Research",desc:"Research into social engineering, manipulation patterns, surveillance, and defensive response.",href:"human-hacking-framework.html"},
 {title:"Auditing & Logging Guidelines",year:"2008",area:"Security Foundations",desc:"Early practitioner guidance for audit design, log management, monitoring, and retention.",href:"auditing-logging-guidelines.html"},
 {title:"RHEL 3.0 Hardening Guidelines",year:"2005",area:"Security Foundations",desc:"The first published research project: minimization and hardening guidance for Red Hat Enterprise Linux.",href:"rhel-hardening-guidelines.html"}
];
let activeFilter="All";const list=document.querySelector("#research-list"),search=document.querySelector("#research-search");
function render(){const q=search.value.trim().toLowerCase();const visible=research.filter(x=>(activeFilter==="All"||x.area===activeFilter)&&`${x.title} ${x.desc} ${x.area}`.toLowerCase().includes(q));list.innerHTML=visible.length?visible.map((x,i)=>`<a class="research-item" href="${x.href}"><span class="item-index">${String(i+1).padStart(2,"0")}</span><div><span class="item-meta">${x.area} · ${x.year}</span><h3>${x.title}</h3><p>${x.desc}</p></div><span aria-hidden="true">↗</span></a>`).join(""):'<p>No research items match that search.</p>'}
search.addEventListener("input",render);document.querySelectorAll("[data-filter]").forEach(btn=>btn.addEventListener("click",()=>{activeFilter=btn.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===btn));render()}));
const menu=document.querySelector(".menu-button"),nav=document.querySelector("#site-nav");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open));menu.querySelector("span").textContent=open?"Close":"Menu"});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.setAttribute("aria-expanded","false");menu.querySelector("span").textContent="Menu"}));render();
